# Overall filter parameters 
min_particles : 500
max_particles : 2000  
kld_err : 0.05
kld_z : 0.99  

update_min_d : 0.1

resample_interval: 1

transform_tolerance: 1.0

recovery_alpha_slow : 0.001 
recovery_alpha_fast : 0.1  

initial_pose_x : 0.0
initial_pose_y : 0.0
initial_pose_a : 0.0

update_min_a: 0.3927

gui_publish_rate : 10.0

use_map_topic: False
first_map_only: False

# Laser model parameters 
laser_min_range : 0.1
laser_max_range : 30.0
laser_max_beams : 720
laser_z_hit : 0.5  
laser_z_short : 0.05 
laser_z_max : 0.05
laser_z_rand : 0.5 
laser_sigma_hit : 0.2 
laser_lambda_short : 0.1 
laser_likelihood_max_dist : 2.0 
expected_laser_freq: 5.0
laser_model_type : likelihood_field  

# Odometry model parameters 
odom_model_type : diff
odom_alpha1 : 0.2
odom_alpha2 : 0.2
odom_alpha3 : 0.2 
odom_alpha4 : 0.2
odom_alpha5 : 0.1 

odom_update_interval: 0.1
auto_update_noise: 0.0

odom_frame_id : odom
base_frame_id : base_link
global_frame_id : map
